name: gitrun
description: Deploy a JIT Github runner in the ai4eosc platform
author: Karlsruhe Institute of Technology

runs:
  using: composite
  steps:
    - name: Print error incorrect branch version
      id: error-branch
      shell: bash
      run: |
        echo "Error: Incorrect branch version"
        echo "Please use @github-setup and @github-clean to setup and clean the runner"
        exit 1
