name: gitrun-clean
description: Deploy a JIT Github runner in the ai4eosc platform
author: Karlsruhe Institute of Technology

inputs:
  api-token:
    description: "The token to use to retrieve the JIT configuration"
    required: true
  runner-id:
    description: The runner id for the repository
    required: true

runs:
  using: composite
  steps:
    - name: Remove runner if deployment fails
      if: ${{ failure() || cancelled() }}
      shell: bash
      run: |
        STATUS=$(curl -L --request DELETE \
          --url https://api.github.com/repos/${{ github.repository }}/actions/runners/${{ inputs.runner-id }} \
          --header 'Accept: application/vnd.github+json' \
          --header 'Authorization: Bearer ${{ inputs.api-token }}' \
          --header 'X-GitHub-Api-Version: 2022-11-28' \
          --write-out %{http_code} --silent --output /dev/null)
        echo "Request status: $STATUS"
        if [[ $STATUS != 204 && $STATUS != 404 ]]; then
          echo "Request failed" && exit 1
        fi
