# https://docs.github.com/en/rest/actions/self-hosted-runners?apiVersion=2022-11-28#delete-a-self-hosted-runner-from-a-repository
name: Remove Runner configuration
description: Github Action to remove a runner from repository
author: Karlsruhe Institute of Technology

inputs:
  api-token:
    description: Access token to use for the request
    required: true

  runner-id:
    description: The runner id for the repository
    required: true

runs:
  using: composite
  steps:
    - id: delete-runner
      shell: bash
      run: |
        RESPONSE=$(curl -L --request DELETE \
          --url https://api.github.com/repos/${{ github.repository }}/actions/runners/${{ inputs.runner-id }} \
          --header 'Accept: application/vnd.github+json' \
          --header 'Authorization: Bearer ${{ inputs.api-token }}' \
          --header 'X-GitHub-Api-Version: 2022-11-28' \
          --silent --show-error)
        if [[ $RESPONSE == *"200 OK"* ]]; then
          echo "found=true" >> $GITHUB_OUTPUT
        elif [[ $RESPONSE == *"404 Not Found"* ]]; then
          echo "found=false" >> $GITHUB_OUTPUT
        else
          echo "Request failed" && exit 1
        fi
