name: Runner ai4eosc
description: Github Action producing a runner in the AI4EOSC platform
author: Karlsruhe Institute of Technology

inputs:
  config:
    description: The jit configuration string to use
    required: true
  at:
    description: Access token to use for the request
    required: true
  vo:
    description: The VO to use to retrieve the access token
    required: true

outputs:
  container-id:
    description: The container id in the platform
    value: ${{ steps.deploy-container.outputs.container-id }}

runs:
  using: composite
  steps:
    - id: deploy-container
      shell: bash
      run: |
        SERVICE_CALL="deepaas --jitconfig=${{ inputs.config }}"
        JOB_ID=$(curl --request 'POST' \
          --url https://api.cloud.ai4eosc.eu/v1/deployments/modules/?vo=${{ inputs.vo }} \
          --header 'accept: application/json' \
          --header 'Authorization: Bearer ${{ inputs.at }}' \
          --header 'Content-Type: application/json' \
          --fail-with-body --silent --show-error \
          --insecure \
          --data '{
            "general":{
                "docker_image": "boressan/gitrun",
                "service": "'"$SERVICE_CALL"'"
            },
            "hardware": {
                "cpu_num": 4
            }
        }' | jq -re .job_ID)
        echo "container-id=$JOB_ID" >> $GITHUB_OUTPUT
