# https://docs.github.com/en/rest/actions/self-hosted-runners?apiVersion=2022-11-28#create-configuration-for-a-just-in-time-runner-for-an-organization
name: Get JIT configuration
description: Github Action to get a JIT configuration to configure a runner
author: Karlsruhe Institute of Technology

inputs:
  api-token:
    description: Access token to use for the request
    required: true

outputs:
  runner-id:
    description: The runner id for the repository
    value: ${{ steps.get-jitconfig.outputs.runner_id }}

  jitconfig:
    description: The JIT configuration for the runner
    value: ${{ steps.get-jitconfig.outputs.jitconfig }}

runs:
  using: composite
  steps:
    - id: get-jitconfig
      shell: bash
      run: |
        RESPONSE=$(curl -L --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/actions/runners/generate-jitconfig \
          --header 'Accept: application/vnd.github+json' \
          --header 'Authorization: Bearer ${{ inputs.api-token }}' \
          --header 'X-GitHub-Api-Version: 2022-11-28' \
          --fail-with-body --silent --show-error \
          --data '{
              "name": "'"ai4eosc runner $(uuidgen)"'",
              "runner_group_id": 1,
              "labels": ["self-hosted","ai4eosc"],
              "work_folder": "_work",
              "ephemeral": "true"
            }')
        echo "runner-id=$(echo $RESPONSE | jq -re .runner.id)" >> $GITHUB_OUTPUT
        echo "jitconfig=$(echo $RESPONSE | jq -re .encoded_jit_config)" >> $GITHUB_OUTPUT
