name: Deploy a gitrun container to ai4eosc platform

env:
  repository: "BorjaEst/gitrun"
  VO: "vo.ai4eosc.eu"

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-runner:
    runs-on: ubuntu-latest
    name: Deploy a gitrun container to ai4eosc platform
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Get oidc token from secret mytoken
        id: get-access-token
        uses: BorjaEst/mytoken-action@1.0.0
        with:
          my-token: ${{ secrets.MYTOKEN }}

      - name: Generate a JIT configuration file for a self-hosted runner
        id: get-jitconfig
        uses: ./.github/actions/get-jitconfig
        with:
          repository: ${{ env.repository }}
          api-token: ${{ secrets.APITOKEN }}

      - name: Start runner in ai4eosc platform
        id: start-runner
        uses: ./.github/actions/ai4eosc-start-runner
        with:
          config: ${{ steps.get-jitconfig.outputs.jitconfig }}
          at: ${{ steps.get-access-token.outputs.access-token }}
          vo: ${{ env.VO }}

      - name: Print container public access url
        run: echo "https://api-$RUNNER_ID.deployments.cloud.ai4eosc.eu"
        env:
          RUNNER_ID: ${{ steps.start-runner.outputs.container-id }}

  run-on-runner:
    runs-on: [self-hosted, ai4eosc]
    needs: deploy-runner
    steps:
      - run: echo Hello world!
      - run: sleep 100
