name: Deploy a gitrun container to ai4eosc platform

on:
  workflow_dispatch:
    inputs:
      vo:
        description: "The VO to use"
        type: string
        default: "vo.ai4eosc.eu"

permissions:
  contents: read

jobs:
  deploy-runner:
    runs-on: ubuntu-latest
    name: Deploy a gitrun container to ai4eosc platform
    outputs:
      container-id: ${{ steps.start-runner.outputs.container-id }}
      runner-id: ${{ steps.start-runner.outputs.runner-id }}
    steps:
      - name: Start runner in ai4eosc platform
        id: start-runner
        uses: BorjaEst/gitrun@github-action
        with:
          my-token: ${{ secrets.MYTOKEN }}
          api-token: ${{ secrets.APITOKEN }}
          vo: ${{ inputs.VO }}

  run-on-runner:
    runs-on: [self-hosted, ai4eosc]
    needs: deploy-runner
    steps:
      - run: echo Hello world!
      - run: sleep 100

  # clean-up-runner:
  #   runs-on: ubuntu-latest
  #   needs: [deploy-runner, run-on-runner]
  #   if: ${{ failure() || cancelled() }}
  #   steps:
  #     - name: Remove the runner from the repository
  #       id: clean-runner
  #       uses: BorjaEst/gitrun@github-clean
  #       with:
  #         api-token: ${{ secrets.MYTOKEN }}
  #         runner-id: ${{ needs.deploy-runner.outputs.runner-id }}
