name: Deploy a gitrun container to ai4eosc platform

env:
  repository: "BorjaEst/gitrun"
  VO: "vo.ai4eosc.eu"

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-runner:
    runs-on: ubuntu-latest
    name: Deploy a gitrun container to ai4eosc platform
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Exchange APITOKEN by registration TOKEN
        id: get-regtoken
        run: |
          REGTOKEN=$(curl -L --request POST \
            --url https://api.github.com/repos/${{ env.repository }}/actions/runners/registration-token \
            --header 'Accept: application/vnd.github+json' \
            --header 'Authorization: Bearer ${{ secrets.APITOKEN }}' \
            --header 'X-GitHub-Api-Version: 2022-11-28' \
            --fail-with-body --silent --show-error | jq -re .token)
          echo "::add-mask::$REGTOKEN"
          echo "regtoken=$REGTOKEN" >> $GITHUB_OUTPUT

      - name: Generate a JIT configuration file for a self-hosted runner
        id: get-jitconfig
        run: |
          JITCONFIG=$(curl -L --request POST \
            --url https://api.github.com/repos/${{ env.repository }}/actions/runners/generate-jitconfig \
            --header 'Accept: application/vnd.github+json' \
            --header 'Authorization: Bearer ${{ secrets.APITOKEN }}' \
            --header 'X-GitHub-Api-Version: 2022-11-28' \
            --fail-with-body --silent --show-error \
            --data '{
                "name": "'"ai4eosc runner $(uuidgen)"'",
                "runner_group_id": 1,
                "labels": ["self-hosted","ai4eosc"],
                "work_folder": "_work",
                "ephemeral": "true"
              }'| jq -re .encoded_jit_config)
          echo "jitconfig=$JITCONFIG" >> $GITHUB_OUTPUT

      - name: Get oidc token from secret mytoken
        id: get-access-token
        uses: BorjaEst/mytoken-action@1.0.0
        with:
          my-token: ${{ secrets.MYTOKEN }}

      - name: Start runner in ai4eosc platform
        id: start-runner
        uses: ./.github/actions/ai4eosc-start-runner
        with:
          config: ${{ steps.get-jitconfig.outputs.jitconfig }}
          at: ${{ steps.get-access-token.outputs.access-token }}
          rt: ${{ steps.get-regtoken.outputs.regtoken }}
          vo: ${{ env.VO }}
          url: https://github.com/${{ env.repository }}

      - name: Print container public access url
        run: echo "https://api-$RUNNER_ID.deployments.cloud.ai4eosc.eu"
        env:
          RUNNER_ID: ${{ steps.start-runner.outputs.container-id }}

  run-on-runner:
    runs-on: [self-hosted, ai4eosc]
    needs: deploy-runner
    steps:
      - run: echo Hello world!
      - run: sleep 100
